name: Update GitHub Profile with Recent Activity

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Get recent activity from GitHub API
        run: |
          curl -s "https://api.github.com/users/taskmovenis/events" | jq '.[:5] | .[] | {type, repo: (.repo.name // "Sin nombre"), created_at: (.created_at // "fecha no disponible"), payload}' > recent_activity.json

      - name: Generate recent activity markdown
        run: |
          echo "### Últimas Actividades:" > updated_activity.md
          cat recent_activity.json | jq -r '.[] | "- \(.type) en el repositorio [\(.repo)] a las \(.created_at)"' >> updated_activity.md

      - name: Get repository statistics
        run: |
          repos=("LinuxGuide" "LinuxCommands")  # Lista de repositorios de Theritex
          for repo in "${repos[@]}"; do
            stars=$(curl -s "https://api.github.com/repos/Theritex/$repo" | jq '.stargazers_count')
            forks=$(curl -s "https://api.github.com/repos/Theritex/$repo" | jq '.forks_count')
            echo "### $repo" >> updated_activity.md
            echo "- Estrellas: $stars" >> updated_activity.md
            echo "- Forks: $forks" >> updated_activity.md
            echo "" >> updated_activity.md
          done
          
      - name: Overwrite README.md with recent activity
        run: |
          cp updated_activity.md README.md

      - name: Commit and push changes
        run: |
          git config --global user.email "160645558+taskmovenis@users.noreply.github.com"
          git config --local user.name "taskmovenis"
          git add README.md
          git commit -m "Actualización automática del perfil"
          git push origin main