name: Update GitHub Profile with Recent Activity

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta a la medianoche
    - cron: '0 12 * * *'  # Ejecuta al mediodía
    - cron: '0 18 * * *'  # Ejecuta por la tarde
  workflow_dispatch:  # Permite ejecución manual

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener las últimas 5 contribuciones desde la API de GitHub
      - name: Get recent activity from GitHub API
        run: |
          curl -s "https://api.github.com/users/taskmovenis/events" | jq '.[:5] | .[] | {type, repo: .repo.name, payload}' > recent_activity.json

      # Paso 2: Formatear y generar un archivo de Markdown con las actividades recientes
      - name: Generate recent activity markdown
        run: |
          echo "### Últimas Actividades:" > updated_activity.md  # Limpiar el archivo y agregar título
          cat recent_activity.json | jq -r '.[] | "- \(.type) en el repositorio [\(.repo)]"' >> updated_activity.md

      # Paso 3: Obtener estadísticas de repositorios
      - name: Get repository statistics
        run: |
          repos=("LinuxGuide" "LinuxCommands")  # Lista de proyectos de otro usuario o empresa
          for repo in "${repos[@]}"; do
            stars=$(curl -s "https://api.github.com/repos/Theritex/$repo" | jq '.stargazers_count')
            forks=$(curl -s "https://api.github.com/repos/Theritex/$repo" | jq '.forks_count')
            echo "### $repo" >> updated_activity.md
            echo "- Estrellas: $stars" >> updated_activity.md
            echo "- Forks: $forks" >> updated_activity.md
            echo "" >> updated_activity.md
          done

      # Paso 4: Reemplazar el contenido del README.md con las últimas actividades
      - name: Overwrite README.md with recent activity
        run: |
          cp updated_activity.md README.md  # Sobrescribir el README.md

      # Paso 5: Hacer commit y push de los cambios al repositorio
      - name: Commit and push changes
        run: |
          git config --global user.email "160645558+taskmovenis@users.noreply.github.com"
          git config --local user.name "taskmovenis"
          git add README.md
          git commit -m "Actualización automática del perfil"
          git push origin main